Add nanoflow event
FlockOfBirds/rich-text pull request #11
Opened 2018-04-16 11:45 UTC by McDoyen

2018-05-04 09:42 UTC, jseremba requested changes

2018-05-04 09:42 UTC, jseremba commented on src/RichText.xml
> +    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAA2tJREFUeAHtW72OEzEQ3g1IQJn+gI4WpGsQT0AaREESeIGrrsxrnES9DbRJQDrRHC0010JDjY68ANLBQZPc571dnT32xo4zXhzWadZjz+839uyPnSxLv4RAQqDLC
Invalid icon, use
`iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAVFBMVEUAAABVVVVmZmZVVVVXV1dVVVVYWFhVVVVJsvhXV1dVVVVWVlZVVVVVVVVWVlZWVlZWVlZWVlZWVlZWVlZVVVVWVlZJsPdVVVVVVVVVVVVIsPdVVVVYxw9VAAAAGnRSTlMAAwoeLz9ASElJUVNvcoygqazH0NXf4+Pk+DNXn6MAAADwSURBVHja7ZXrDoIwDEanoAyGctOi7P3fU8C4suA65gxq3PnVfKEnbJSUBe5s8rJ6UOwYQdpKRZuqOJcTrhEhGPrRoOJSTskIgdRQcaXF4jXBUQzUfXWIzWDbTCBURfEjgnNjxi6wfAVCUFcDFxSsOgeFFifuo7y/SuS0df+ZWJQJIcbXF0nfz6F7AnA8huWGsV83LBZ0BtYVzKpVBaAuDNvA5RI5AEeBllkFCAoUQRAEQfC/Ag64D9wFuB/gIwL7Eewr075ciaXtuN6lBiWQGoa4ISAEWFHgk18tiAkWCRjBmwW+c+Av8B5l/58pMHID+k6HUjc3bmAAAAAASUVORK5CYII=`

2018-05-04 09:42 UTC, jseremba commented on src/RichText.xml
> +            <description>Nanoflow will be triggered when focus is lost and the content has changed</description>
i think description should be 
`Nanoflow that will be triggered when focus is lost and the content has changed` and this applies to the microflow

2018-05-04 09:42 UTC, jseremba commented on src/components/RichTextContainer.ts
> +                error: error => window.mx.ui.error(`Error while executing nanoflow: + ${onChangeNanoflow} : ${error.message}`),
Re-format error to
`window.mx.ui.error(`Error while executing nanoflow: ${onChangeNanoflow} : ${error.message}``
Plus sign not required for template strings

2018-05-23 14:52 UTC, Andries-Smit commented
Merge via upstream

2018-05-23 14:52 UTC, closed without merging