feature/editor-modes
FlockOfBirds/rich-text pull request #2
Opened 2017-07-03 13:41 UTC by edwinmp

- Add the simple, advanced & custom editor modes
- Implement read-only & no context handling

2017-07-04 07:50 UTC, Andries-Smit requested changes

2017-07-04 07:50 UTC, Andries-Smit commented on Gruntfile.js
> +"use strict";
Update like 
https://github.com/FlockOfBirds/badge/blob/feature/WM-conditional-visibility/Gruntfile.js

2017-07-04 07:50 UTC, Andries-Smit commented on README.md
> +Mendix 7.1
7.4

2017-07-04 07:50 UTC, Andries-Smit commented on README.md
> +Rich inline text editing
Toolbar or inline

2017-07-04 07:50 UTC, Andries-Smit commented on README.md
> +Place the widget in the context of an object that has a string attribute.
Technical, please explain in layman terms

2017-07-04 07:50 UTC, Andries-Smit commented on package.json
> +  "description": "Rich inline text editing",
Update description

2017-07-04 07:50 UTC, Andries-Smit commented on package.json
> +  "repository": {
Pre-push run test?

2017-07-04 07:50 UTC, Andries-Smit commented on package.json
> +    "url": "https://github.com/mendixlabs/TextEditor/issues"
Update URL to new URL

2017-07-04 07:50 UTC, Andries-Smit commented on package.json
> +    "webpack": "^2.6.0",
update to latest webpack

2017-07-04 07:50 UTC, Andries-Smit commented on package.json
> +    "webpack-bundle-analyzer": "^2.8.2",
Remove

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.webmodeler.ts
> +            readOnly: true,
Should be not readonly, overlay of WM will disable it. 
Readonly based on its settings

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.webmodeler.ts
> +            value: valueAttribute ? "[" + valueAttribute + "]" : props.stringAttribute
or empty? `""`

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +    <name>RichText</name>
`Rich Text`

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +    <description>Rich inline text editing</description>
Update description

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>Whether the text editor should be always visible or only popup when text is selected for
Improve description

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <caption>Editor mode</caption>
'Toolbar options'

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>
Explain custom

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>Whether a non-responsive editor is shown or just the formatted text</description>
Could be better no no `Whether `

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>The attribute that contains the rich text</description>
HTML ?

2017-07-04 07:50 UTC, Andries-Smit commented on README.md
> +
Missing some

2017-07-04 07:50 UTC, Andries-Smit commented on README.md
> +
HTML reference?>

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +                    <description/>
Explain, spacer

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>Microflow to trigger when the editor is changed</description>
The `the editor` is not changes, the text/content.
Only trigger when value!=value

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +
Remove white line

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +            this.props.onChange((this.quill as any).container.firstChild.innerHTML);
Extract parameter above
`const value = (this.quill as any).container.firstChild.innerHTML;`

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +            this.quill.clipboard.dangerouslyPasteHTML(props.value);
Apply Maintain  selection trick from other lib

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +    private getEditorModules(): Quill.StringMap {
modules or options?

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +    private renderEditor(props: RichTextProps) {
Function does not reder... setup a better name?

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +
remove white lines?

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichText.ts
> +    private static processCustomOptions(options: Array<{ option: string }>): any[] {
Think we can come up with a type... in a later release...

2017-07-04 07:50 UTC, Andries-Smit commented on src/components/RichTextContainer.ts
> +                params: {
Use params or context. when using params remove the context above

2017-07-04 07:50 UTC, Andries-Smit commented on src/ui/RichText.scss
> +            min-height: 100px;
Check with UX about height props

2017-07-04 07:50 UTC, Andries-Smit commented on tsconfig.json
> +    "noImplicitAny": true,
`strict` mode?

2017-07-04 07:50 UTC, Andries-Smit commented on webpack.config.js
> +const pkg = require("./package");
Add white line befire

2017-07-04 07:50 UTC, Andries-Smit commented on typings/rich-text.d.ts
> +declare function require(name: string): string;
Can we do this with tsconfig file?

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +        <property key="visibility" type="enumeration" defaultValue="snow">
Rename to theme

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <caption>Visibility</caption>
Give better name for a user?

2017-07-04 07:50 UTC, Andries-Smit commented on src/RichText.xml
> +            <category>Display</category>
`<category>Appearance</category>`

2017-07-04 13:10 UTC, edwinmp commented on Gruntfile.js
> +"use strict";
Done!

2017-07-04 13:11 UTC, edwinmp commented on README.md
> +Rich inline text editing
Done!

2017-07-04 13:14 UTC, edwinmp commented on README.md
> +
* Edit selected text
* HTML output of formatted text
* Show editor options either on a toolbar or as a bubble

2017-07-04 13:15 UTC, edwinmp commented on README.md
> +Mendix 7.1
Settled for 7.3 on account of the web modeler issues on 7.4.

2017-07-04 13:25 UTC, edwinmp commented on README.md
> +Place the widget in the context of an object that has a string attribute.
Place the widget in a data view, list view or template grid with a data source that has a string attribute.

2017-07-04 13:25 UTC, edwinmp commented on package.json
> +  "description": "Rich inline text editing",
Done.

2017-07-04 13:31 UTC, edwinmp commented on package.json
> +  "repository": {
Done.

2017-07-04 13:33 UTC, edwinmp commented on package.json
> +    "url": "https://github.com/mendixlabs/TextEditor/issues"
Done!

2017-07-04 13:37 UTC, edwinmp commented on package.json
> +    "webpack": "^2.6.0",
Done!

2017-07-04 13:37 UTC, edwinmp commented on package.json
> +    "webpack-bundle-analyzer": "^2.8.2",
Done!

2017-07-04 13:38 UTC, edwinmp commented on src/RichText.webmodeler.ts
> +            readOnly: true,
Done!

2017-07-04 13:45 UTC, edwinmp commented on src/RichText.xml
> +    <name>RichText</name>
Changed!

2017-07-04 13:45 UTC, edwinmp commented on src/RichText.xml
> +    <description>Rich inline text editing</description>
Done!

2017-07-04 13:47 UTC, edwinmp commented on src/RichText.xml
> +        <property key="visibility" type="enumeration" defaultValue="snow">
Done!

2017-07-04 13:48 UTC, edwinmp commented on src/RichText.xml
> +            <caption>Visibility</caption>
Done.

2017-07-04 13:49 UTC, edwinmp commented on src/RichText.xml
> +            <category>Display</category>
Done!

2017-07-04 13:49 UTC, edwinmp commented on src/RichText.xml
> +            <description>Whether the text editor should be always visible or only popup when text is selected for
Done!

2017-07-04 13:59 UTC, edwinmp commented on src/RichText.xml
> +            <caption>Editor mode</caption>
Editor Options

2017-07-04 13:59 UTC, edwinmp commented on src/RichText.xml
> +            <description>
Done.

2017-07-04 14:00 UTC, edwinmp commented on src/RichText.xml
> +            <description>Whether a non-responsive editor is shown or just the formatted text</description>
Done!

2017-07-04 14:00 UTC, edwinmp commented on src/RichText.xml
> +            <description>The attribute that contains the rich text</description>
Done!

2017-07-04 14:02 UTC, edwinmp commented on src/RichText.xml
> +                    <description/>
Done!

2017-07-04 14:03 UTC, edwinmp commented on src/RichText.xml
> +            <description>Microflow to trigger when the editor is changed</description>
Done!

2017-07-04 14:06 UTC, edwinmp commented on src/components/RichText.ts
> +    private renderEditor(props: RichTextProps) {
setUpEditor...?

2017-07-04 14:06 UTC, edwinmp commented on src/components/RichText.ts
> +
Done!

2017-07-04 14:07 UTC, edwinmp commented on src/components/RichText.ts
> +            this.props.onChange((this.quill as any).container.firstChild.innerHTML);
Done!

2017-07-04 14:34 UTC, edwinmp commented on src/components/RichText.ts
> +            this.quill.clipboard.dangerouslyPasteHTML(props.value);
Applied but still needs some testing... selection seems to always be null locally.

2017-07-04 14:37 UTC, edwinmp commented on src/components/RichText.ts
> +    private getEditorModules(): Quill.StringMap {
Done!

2017-07-04 14:41 UTC, edwinmp commented on src/components/RichText.ts
> +
Done!

2017-07-04 14:47 UTC, edwinmp commented on src/components/RichText.ts
> +    private static processCustomOptions(options: Array<{ option: string }>): any[] {
Removed it, cos it was not very useful since we only ever check. The other time we use an index signature to retrieve values.

2017-07-04 14:49 UTC, edwinmp commented on src/components/RichTextContainer.ts
> +                params: {
Done!

2017-07-04 14:50 UTC, edwinmp commented on tsconfig.json
> +    "noImplicitAny": true,
Done!

2017-07-04 14:50 UTC, edwinmp commented on webpack.config.js
> +const pkg = require("./package");
Done!

2017-07-04 14:51 UTC, edwinmp commented on typings/rich-text.d.ts
> +declare function require(name: string): string;
No idea what you mean...

2017-07-13 11:19 UTC, Andries-Smit requested changes
Will continue after external review

2017-07-13 11:19 UTC, Andries-Smit commented on Gruntfile.js
> +            updateWidgetFiles: {
Watch `"./src/**/*" `

2017-07-13 11:19 UTC, Andries-Smit commented on Gruntfile.js
> +            sourceFiles: {
Remove

2017-07-13 11:19 UTC, Andries-Smit commented on Gruntfile.js
> +            source: {
remove

2017-07-13 11:19 UTC, Andries-Smit commented on README.md
> +Place the widget in a data view, list view or template grid with a data source that has a string attribute.
`that has a string attribute.`
=> `and select the 'Value attribute' that contains the editable text`

2017-07-13 11:19 UTC, Andries-Smit commented on README.md
> +[https://github.com/MendixLabs/rich-text/releases/download/v1.0.0/TestRichText.mpk](https://github.com/MendixLabs/rich-text/releases/download/v1.0.0/TestRichText.mpk)
Use relative links when possible
`Or get the test project from https://github.com/mendixlabs/google-maps/releases/latest`

2017-07-13 11:19 UTC, Andries-Smit commented on package.json
> +  "repository": {
Will work on build server

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.webmodeler.ts
> +import { render, unmountComponentAtNode } from "react-dom";
Make react 16 compatible.

2017-07-13 11:19 UTC, Andries-Smit commented on README.md
> +
`* -, space : start list`
`* tab: not functional, go to next input field`

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.webmodeler.ts
> +    private getRichTextNode(node: HTMLDivElement) {
`node: HTMLDivElement | null` think the latest react typing is...

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.webmodeler.ts
> +            hasContext: true,
This naming is not functional, more like a Mendix naming

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <caption>Theme</caption>
Caption `Theme` is does not match the description

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <caption>Editor options</caption>
`Text formatting options` ?

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>Advanced shows all available options while custom lets u choose which buttons to show</description>
Formatting options shown in the toolbar or bubble

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <description/>
Explain that `default` is based on the page settings and attribute write access.

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <description/>
Explain; when max line is larger that min lines the input will auto grow.
Explain When 0

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <description/>
Explain When 0

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>The attribute that contains the HTML output</description>
`output` or `text`

2017-07-13 11:19 UTC, Andries-Smit commented on src/RichText.xml
> +            <caption>Options</caption>
`Format options` ?

2017-07-20 05:07 UTC, edwinmp commented on Gruntfile.js
> +            updateWidgetFiles: {
Done.

2017-07-20 05:07 UTC, edwinmp commented on Gruntfile.js
> +            sourceFiles: {
Done.

2017-07-20 05:17 UTC, edwinmp commented on Gruntfile.js
> +            source: {
Done.

2017-07-20 05:20 UTC, edwinmp commented on README.md
> +
Done!

2017-07-20 05:21 UTC, edwinmp commented on README.md
> +Place the widget in a data view, list view or template grid with a data source that has a string attribute.
Done!

2017-07-20 05:22 UTC, edwinmp commented on README.md
> +[https://github.com/MendixLabs/rich-text/releases/download/v1.0.0/TestRichText.mpk](https://github.com/MendixLabs/rich-text/releases/download/v1.0.0/TestRichText.mpk)
Don't know how to use relative links in this case. These files aren't part of the repo's folder structure.

2017-07-20 05:25 UTC, edwinmp commented on src/RichText.webmodeler.ts
> +import { render, unmountComponentAtNode } from "react-dom";
Done.

2017-07-20 05:25 UTC, edwinmp commented on src/RichText.webmodeler.ts
> +    private getRichTextNode(node: HTMLDivElement) {
Removed.

2017-07-20 05:29 UTC, edwinmp commented on src/RichText.xml
> +            <caption>Theme</caption>
Replaced with `Show as`

2017-07-20 05:31 UTC, edwinmp commented on src/RichText.xml
> +            <description>Advanced shows all available options while custom lets u choose which buttons to show</description>
Changed!

2017-07-20 05:32 UTC, edwinmp commented on src/RichText.xml
> +            <description/>
Done!

2017-07-20 05:35 UTC, edwinmp commented on src/RichText.xml
> +            <description/>
Done!

2017-07-20 05:38 UTC, edwinmp commented on src/RichText.xml
> +            <description/>
Done!

2017-07-20 05:40 UTC, edwinmp commented on src/RichText.xml
> +            <description>The attribute that contains the HTML output</description>
??

2017-07-20 05:42 UTC, edwinmp commented on src/RichText.xml
> +            <caption>Options</caption>
Done.

2017-07-20 08:35 UTC, Andries-Smit commented on README.md
> +[https://github.com/MendixLabs/rich-text/releases/download/v1.0.0/TestRichText.mpk](https://github.com/MendixLabs/rich-text/releases/download/v1.0.0/TestRichText.mpk)
Its relative to the release version, but not the repo.
`Create a Mendix test project in the dist folder and rename its root folder to MxTestProject. Changes to the widget code shall be automatically pushed to this test project. Or get the test project from https://github.com/mendixlabs/rich-text/releases/latest`

2017-07-20 08:37 UTC, Andries-Smit commented
Please update your asset screenshots they do not match with the current versions of the widget.xml
Or if we dont use them.. remove them.. as they will always be out of date and forgotten.

2017-07-20 08:40 UTC, Andries-Smit commented on src/RichText.xml
> +            <description>The attribute that contains the HTML output</description>
Output is not understood by the user, please change to `text`

2017-07-20 08:41 UTC, Andries-Smit commented on src/components/Alert.ts
> +export { Alert, AlertProps };
Move export inline

2017-07-20 08:46 UTC, Andries-Smit commented on src/components/RichText.ts
> +            const value = (this.quill as any).container.firstChild.innerHTML;
`as any` Why? and is this save?

2017-07-20 08:47 UTC, Andries-Smit commented on src/components/RichText.ts
> +
remove empty line

2017-07-20 08:48 UTC, Andries-Smit commented on src/components/RichText.ts
> +        if (this.props.editorOption === "extended") {
could be `} else if (`

2017-07-20 08:49 UTC, Andries-Smit commented on src/components/RichText.ts
> +        return getToolbar(this.props.customOptions || null);
`this.props.customOptions` will receive an empty array from Mendix when not items are added in the modeler, so `|| null` will never be called

2017-07-20 08:53 UTC, Andries-Smit commented on src/utils/ContainerUtils.ts
> +    return mxObject ? mxObject.get(attribute) || defaultValue : defaultValue;
`mxObject && attribute` could be an empty string in attributes if not attribute is selected in the modeler. Maybe not in the case...

2017-07-20 08:56 UTC, Andries-Smit commented on src/components/RichTextContainer.ts
> +            value: String(getValue(props.stringAttribute, "", props.mxObject))
Cast to string you should not initialize a new String object
```value: <string>getValue(props.stringAttribute, "", props.mxObject)```

2017-07-20 08:58 UTC, Andries-Smit commented on src/components/RichTextContainer.ts
> +            value: String(getValue(props.stringAttribute, "", props.mxObject))
some times use `as string` if it makes the code better readable.

2017-07-20 08:58 UTC, Andries-Smit commented on src/components/RichTextContainer.ts
> +                value: String(getValue(newProps.stringAttribute, "", newProps.mxObject))
Same as above please donnot use `String()`

2017-07-20 08:59 UTC, Andries-Smit commented on src/components/RichTextContainer.ts
> +            value: String(getValue(this.props.stringAttribute, "", this.props.mxObject))
no `String(`

2017-07-20 08:59 UTC, Andries-Smit commented on src/components/RichTextContainer.ts
> +
remove new line

2017-07-20 09:10 UTC, edwinmp commented on src/components/Alert.ts
> +export { Alert, AlertProps };
Done!

2017-07-20 10:47 UTC, edwinmp commented on src/components/RichText.ts
> +            const value = (this.quill as any).container.firstChild.innerHTML;
Was the recommended way to do it.
Added typings for it.

2017-07-20 13:56 UTC, edwinmp commented on src/components/RichText.ts
> +        if (this.props.editorOption === "extended") {
Done!

2017-07-20 13:57 UTC, edwinmp commented on src/components/RichText.ts
> +
Done!

2017-07-20 14:06 UTC, edwinmp commented on src/components/RichText.ts
> +        return getToolbar(this.props.customOptions || null);
Made it non-optional.

2017-07-20 14:08 UTC, edwinmp commented on src/utils/ContainerUtils.ts
> +    return mxObject ? mxObject.get(attribute) || defaultValue : defaultValue;
```
export const getValue = (attribute: string, defaultValue: MxValue, mxObject?: mendix.lib.MxObject): MxValue => {
    return mxObject && attribute.trim() ? mxObject.get(attribute) || defaultValue : defaultValue;
};
```

2017-07-20 14:09 UTC, edwinmp commented on src/components/RichTextContainer.ts
> +            value: String(getValue(props.stringAttribute, "", props.mxObject))
`as string` doesn't cast & I needed the cast. Didn't know` <string>` does casting... Nice.

2017-07-20 14:13 UTC, edwinmp commented on src/components/RichTextContainer.ts
> +                value: String(getValue(newProps.stringAttribute, "", newProps.mxObject))
Removed.

2017-07-20 14:14 UTC, edwinmp commented on src/components/RichTextContainer.ts
> +            value: String(getValue(this.props.stringAttribute, "", this.props.mxObject))
Removed.

2017-07-20 14:14 UTC, edwinmp commented on src/components/RichTextContainer.ts
> +
Done!

2017-08-02 07:55 UTC, merged